name: Publish to npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Настраиваем Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch --tags --force

    - name: Удаляем старый тег (если есть)
      run: |
        git tag -d v1.0.37 || true
        git push --delete origin v1.0.37 || true

    - name: Обновляем версию
      run: npm version patch

    - name: Пушим изменения (без триггера workflow)
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git push origin HEAD:main -m "chore: version bump [skip ci]"
        git push --tags
