name: Publish to npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # Полная история для работы с тегами

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Delete existing tag if needed
        run: |
          git tag -d v$(node -p "require('./package.json').version") || true
          git push --delete origin v$(node -p "require('./package.json').version") || true

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version  # Обновляем версию без создания тега
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "Bump version to $VERSION"
          git tag -a v$VERSION -m "Version $VERSION"

      - name: Push changes and tags
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
          git push origin --tags --force

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
