name: Publish to npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get current version
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version safely
        run: |
          # Увеличиваем версию без создания тега
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          # Проверяем существует ли тег
          if git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; then
            echo "::error::Tag v$NEW_VERSION already exists, aborting"
            exit 1
          fi
          
          # Создаем коммит и тег
          git add package.json
          git commit -m "Bump version to $NEW_VERSION"
          git tag -a "v$NEW_VERSION" -m "Version $NEW_VERSION"

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
          git push origin "v$(node -p "require('./package.json').version")"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
